AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create two S3 buckets.

Parameters:
  BucketName1:
    Type: String
    Description: Name for the first S3 bucket
  BucketName2:
    Type: String
    Description: Name for the second S3 bucket

Resources:
  S3BucketOne:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName1
      VersioningConfiguration:
        Status: Enabled

  S3BucketTwo:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName2
      VersioningConfiguration:
        Status: Enabled

Outputs:
  FirstBucket:
    Description: First S3 Bucket Name
    Value: !Ref S3BucketOne

  SecondBucket:
    Description: Second S3 Bucket Name
    Value: !Ref S3BucketTwo
