AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a versioned S3 bucket

Resources:
  FreeS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: akhil-free-bucket-834153250791-ap-south-1
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref FreeS3Bucket
    Description: Name of the created S3 bucket
