AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a free S3 bucket.

Resources:
  MyFreeS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'akhil-free-bucket-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Value: !Ref MyFreeS3Bucket
    Description: Name of the S3 bucket created.
