AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create two S3 buckets accessible only by root user.

Parameters:
  BucketName1:
    Type: String
    Description: Name for the first S3 bucket
  BucketName2:
    Type: String
    Description: Name for the second S3 bucket

Resources:
  S3BucketOne:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName1
      VersioningConfiguration:
        Status: Enabled

  S3BucketOnePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketOne
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${BucketName1}"
              - !Sub "arn:aws:s3:::${BucketName1}/*"
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${BucketName1}"
              - !Sub "arn:aws:s3:::${BucketName1}/*"

  S3BucketTwo:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName2
      VersioningConfiguration:
        Status: Enabled

  S3BucketTwoPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketTwo
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${BucketName2}"
              - !Sub "arn:aws:s3:::${BucketName2}/*"
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "s3:*"
           
